### ISSUE TITLE
[enhancement] Compact mode

### ISSUE THREAD

**Issue by Steelskinz** [cswendrowski/FoundryVTT-mmo-hud#2]
First of, it's a great module, as a long time player of final fantasy series I love it. However it seems to take so much space on the screen when you have a lot of players. It should be nice to add a version more compact if possible.
I mean this is like 1/6 of the screen xD
![image](https://user-images.githubusercontent.com/93941729/212527806-cbcd03b8-e0b4-49b1-ae34-4f9e59103447.png)

**Comment by cswendrowski** [comment]
Added Compact (90%) and Small (80%) modes as options in v1.2.0, let me know if those are still too big
