### ISSUE TITLE
[bug ?] Not actualising Active Effects automatically

### ISSUE THREAD

**Issue by Steelskinz** [cswendrowski/FoundryVTT-mmo-hud#3]
System : DND5e
How to reproduce : Add an effect on an actor. 
How to make it work : You need to clic on the window's module to make it actualize.
![image](https://user-images.githubusercontent.com/93941729/212528201-2b1fc962-87ec-4105-92b8-1b1fca55ed5f.png)
![image](https://user-images.githubusercontent.com/93941729/212528213-f8ef2fe3-461e-4dfd-9895-26b047064ef0.png)

**Comment by cswendrowski** [comment]
Fixed in v1.1.0
