### ISSUE TITLE
[System Request] SWADE

### ISSUE THREAD

**Issue by brunocalado** [cswendrowski/FoundryVTT-mmo-hud#6]
Great module!

Can you make it work for SWADE?

tks

**Comment by cswendrowski** [comment]
Foundry does not support inverse resource bars, but I've added a minor change to invert the bar when `wounds` or `fatigue` are set as resource bars. This is not 100% ideal, but I'm hoping to improve core resource bars in V11 so we can trickle changes downstream:
![image](https://user-images.githubusercontent.com/15639841/212568014-66e93aaf-bdff-4b15-99eb-5f32931fc5e5.png)
